<?php

/**
 * @file
 * OCHA Snap generator module.
 *
 * @TODO
 * - Set sensible default params.
 * - Add caching and direct asset output in this module without the need
 *   for print_pdf module.
 * - Allow footer and header to be configured.
 */

use \Drupal\Component\Utility\UrlHelper;

/**
 * Helper to fetch the snap service endpoint.
 */
function ocha_snap_url() {
  if (!empty(\Drupal::config('ocha_snap.settings')->get('url'))) {
    return \Drupal::config('ocha_snap.settings')->get('url');
  }

  return 'http://localhost:8442/snap';
}

/**
 * Helper to fetch site credentials.
 */
function ocha_snap_credentials() {
  $user = \Drupal::config('ocha_snap.settings')->get('site_user');
  $pass = \Drupal::config('ocha_snap.settings')->get('site_pass');

  if (!empty($user) && !empty($pass)) {
    return [
      'user' => $user,
      'pass' => $pass,
    ];
  }
  return FALSE;
}

/**
 * PDF generator.
 *
 * @param string $url
 *   The URL to generate the PDF or PNG for.
 * @param array $params
 *   An array of optional parameters for the Snap Service request.
 *
 * @return various
 *   A binary file data blob or FALSE if an error occurred.
 */
function ocha_snap($url, array $params = []) {
  // Since Drupal's string translations are set up with this existing string, we
  // allow localization to occur first before doing string substitution to work
  // with the Snap Service.
  $pdf_pagination = t('Page [page] of [topage]');
  $pdf_pagination = str_replace('[page]', '<span class="pageNumber"></span>', $pdf_pagination);
  $pdf_pagination = str_replace('[topage]', '<span class="totalPages"></span>', $pdf_pagination);

  // Construct our PDF header and footer.
  //
  // Note: you CANNOT use remote references such as image URLs or stylesheets,
  // nor can JS be executed in this context. Inline HTML/CSS only!
  $pdf_header = str_replace('[pagination]', $pdf_pagination, ocha_snap_pdf_header());
  $pdf_footer = str_replace('[pagination]', $pdf_pagination, ocha_snap_pdf_footer());

  // Service depends on syslog module. Be a bit sensible.
  if (\Drupal::service('module_handler')->moduleExists('syslog')) {
    $service = \Drupal::config('syslog.settings')->get('identity');
  }
  else {
    $service = 'drupal';
  }

  $default_params = [
    'url'           => $url,
    'service'       => $service,
    'media'         => 'screen',
    'output'        => 'pdf',
    'pdfFormat'     => 'A4',
    'pdfLandscape'  => 'false',
    'pdfBackground' => 'true',
    // Suppress default header by sending space character.
    'pdfHeader'     => $pdf_header,
    'pdfFooter'     => $pdf_footer,
    'pdfMarginTop'  => '24',
    'pdfMarginUnit' => 'px',
    'debug'         => \Drupal::config('ocha_snap.settings')->get('ocha_snap_debug') ? 'true' : 'false',
  ];

  // Apply default parameters in case anything was missing.
  $params += $default_params;

  // If the target site is protected by basic auth, add the required
  // credentials to the request.
  $credentials = ocha_snap_credentials();
  if ($credentials !== FALSE) {
    $params += $credentials;
  }

  // Build the API request.
  $url = ocha_snap_url();
  $url .= '?' . UrlHelper::buildQuery($params);
  $req_params = [
    'headers' => [
      'X-Forwarded-For' => Drupal::request()->getClientIp(),
      'User-Agent'      => $_SERVER['HTTP_USER_AGENT'],
    ],
    'method' => 'POST',
  ];

  // Use CHR if installed, otherwise use Drupal built-in http_request.
  if (\Drupal::service('module_handler')->moduleExists('chr')) {
    $output = chr_curl_http_request($url, $req_params);
  }
  else {
    $output = \Drupal::httpClient()->post($url, $req_params);
  }

  // Basic error checking.
  if ($output->getStatusCode() != 200) {
    \Drupal::logger('ocha_snap')->error('Failed to generate PDF for "%u".', ['%u' => $params['url']]);
    return FALSE;
  }

  return $output->getBody();
}

/**
 * Generate a PDF header snippet.
 */
function ocha_snap_pdf_header() {
  // The default is a single space which suppresses header output.
  $header = \Drupal::config('ocha_snap.settings')->get('ocha_snap_header');

  // If CSS is specified, now would be a good time to inject it.
  if ($css = \Drupal::config('ocha_snap.settings')->get('ocha_snap_css')) {
    $header .= '<style type="text/css">' . $css . '</style>';
  }
  return $header;
}

/**
 * Provide a default PDF footer for compatibility reasons.
 */
function ocha_snap_pdf_footer() {
  if ($footer = \Drupal::config('ocha_snap.settings')->get('ocha_snap_footer')) {
    return $footer;
  }

  return '<footer class="pdf-footer">
  <div class="pdf-footer__left">
    [pagination]
  </div>
</footer>
<style type="text/css">
  *, *:before, *:after {
    box-sizing: border-box;
    -webkit-print-color-adjust: exact;
  }
  .pdf-footer {
    display: table;
    width: 100%;
    margin: 0 5mm;
    white-space: nowrap;

    font-family: Roboto, serif;
    font-weight: 400;
    font-size: 9px;
  }
  .pdf-footer__left,
  .pdf-footer__right {
    display: table-cell;
    vertical-align: bottom;
    width: 49%;
  }
  .pdf-footer__right {
    text-align: right;
  }
</style>';
}

/**
 * Implements hook_print_pdf_available_libs_alter().
 */
function ocha_snap_print_pdf_available_libs_alter(&$pdf_tools) {
  $pdf_tools['ocha_snap|' . check_plain(variable_get('ocha_snap_url'))] = t('OCHA Snap Service (@url)', ['@url' => variable_get('ocha_snap_url')]);
}
